In [1]:
from nba_api.stats.endpoints import leaguedashplayerstats

stats = leaguedashplayerstats.LeagueDashPlayerStats(season='2024-25')
df_players = stats.get_data_frames()[0]
top_players = df_players.sort_values('FGA', ascending=False).head(100)
player_ids = top_players['PLAYER_ID'].tolist()

In [2]:
import time
import pandas as pd
import nba_api.stats.endpoints as endpoints

all_shots = []

for player_id in player_ids:
    try:
        response = endpoints.shotchartdetail.ShotChartDetail(
            team_id = 0,
            player_id = player_id,
            season_nullable = '2024-25',
            context_measure_simple = 'FGA'
        )
        df = response.get_data_frames()[0]
        all_shots.append(df)
        time.sleep(0.6)  # Sleep to avoid hitting rate limits
    except Exception as e:
        print(f"Error fetching data for player ID {player_id}: {e}")

# Combine all shot data into a single DataFrame
full_df = pd.concat(all_shots, ignore_index=True)
full_df.to_csv('nba_shot_data_2024_25.csv', index=False)

In [3]:
import pandas as pd

df = pd.read_csv('nba_shot_data_2024_25.csv')
print(df.shape)
print(df.isnull().sum())

(101207, 24)
GRID_TYPE              0
GAME_ID                0
GAME_EVENT_ID          0
PLAYER_ID              0
PLAYER_NAME            0
TEAM_ID                0
TEAM_NAME              0
PERIOD                 0
MINUTES_REMAINING      0
SECONDS_REMAINING      0
EVENT_TYPE             0
ACTION_TYPE            0
SHOT_TYPE              0
SHOT_ZONE_BASIC        0
SHOT_ZONE_AREA         0
SHOT_ZONE_RANGE        0
SHOT_DISTANCE          0
LOC_X                  0
LOC_Y                  0
SHOT_ATTEMPTED_FLAG    0
SHOT_MADE_FLAG         0
GAME_DATE              0
HTM                    0
VTM                    0
dtype: int64

In [4]:
df.drop(columns = [
    'GRID_TYPE', 'GAME_EVENT_ID', 'TEAM_ID', 'TEAM_NAME', 
    'HTM', 'VTM', 'GAME_DATE', 'SHOT_ATTEMPTED_FLAG' 
])

,GAME_ID,PLAYER_ID,PLAYER_NAME,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,EVENT_TYPE,ACTION_TYPE,SHOT_TYPE,SHOT_ZONE_BASIC,SHOT_ZONE_AREA,SHOT_ZONE_RANGE,SHOT_DISTANCE,LOC_X,LOC_Y,SHOT_MADE_FLAG
0,22400018,1628983,Shai Gilgeous-Alexander,1,10,27,Missed Shot,Turnaround Fadeaway shot,2PT Field Goal,In The Paint (Non-RA),Center(C),8-16 ft.,10,-25,97,0
1,22400018,1628983,Shai Gilgeous-Alexander,1,8,38,Missed Shot,Pullup Jump shot,2PT Field Goal,Mid-Range,Right Side(R),16-24 ft.,17,168,64,0
2,22400018,1628983,Shai Gilgeous-Alexander,1,7,14,Made Shot,Step Back Jump shot,3PT Field Goal,Above the Break 3,Left Side Center(LC),24+ ft.,26,-93,244,1
3,22400018,1628983,Shai Gilgeous-Alexander,1,6,32,Made Shot,Driving Finger Roll Layup Shot,2PT Field Goal,Restricted Area,Center(C),Less Than 8 ft.,0,0,6,1
4,22400018,1628983,Shai Gilgeous-Alexander,1,4,54,Made Shot,Step Back Jump shot,2PT Field Goal,Mid-Range,Right Side Center(RC),16-24 ft.,20,141,144,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101202,22401226,1628374,Lauri Markkanen,2,1,43,Made Shot,Tip Dunk Shot,2PT Field Goal,Restricted Area,Center(C),Less Than 8 ft.,0,0,0,1
101203,22401226,1628374,Lauri Markkanen,3,11,32,Made Shot,Jump Shot,3PT Field Goal,Right Corner 3,Right Side(R),24+ ft.,23,230,22,1
101204,22401226,1628374,Lauri Markkanen,3,4,30,Missed Shot,Jump Shot,3PT Field Goal,Above the Break 3,Right Side Center(RC),24+ ft.,27,132,239,0
101205,22401226,1628374,Lauri Markkanen,3,2,41,Missed Shot,Running Jump Shot,3PT Field Goal,Above the Break 3,Right Side Center(RC),24+ ft.,26,197,176,0
101206,22401226,1628374,Lauri Markkanen,3,2,30,Made Shot,Cutting Layup Shot,2PT Field Goal,Restricted Area,Center(C),Less Than 8 ft.,3,-9,30,1

In [5]:
df['TIME_REMAINING_SEC'] = df['MINUTES_REMAINING'] * 60 + df['SECONDS_REMAINING']
df.drop(columns=['MINUTES_REMAINING', 'SECONDS_REMAINING'])

,GRID_TYPE,GAME_ID,GAME_EVENT_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_NAME,PERIOD,EVENT_TYPE,ACTION_TYPE,...,SHOT_ZONE_RANGE,SHOT_DISTANCE,LOC_X,LOC_Y,SHOT_ATTEMPTED_FLAG,SHOT_MADE_FLAG,GAME_DATE,HTM,VTM,TIME_REMAINING_SEC
0,Shot Chart Detail,22400018,17,1628983,Shai Gilgeous-Alexander,1610612760,Oklahoma City Thunder,1,Missed Shot,Turnaround Fadeaway shot,...,8-16 ft.,10,-25,97,1,0,20241115,OKC,PHX,627
1,Shot Chart Detail,22400018,35,1628983,Shai Gilgeous-Alexander,1610612760,Oklahoma City Thunder,1,Missed Shot,Pullup Jump shot,...,16-24 ft.,17,168,64,1,0,20241115,OKC,PHX,518
2,Shot Chart Detail,22400018,56,1628983,Shai Gilgeous-Alexander,1610612760,Oklahoma City Thunder,1,Made Shot,Step Back Jump shot,...,24+ ft.,26,-93,244,1,1,20241115,OKC,PHX,434
3,Shot Chart Detail,22400018,66,1628983,Shai Gilgeous-Alexander,1610612760,Oklahoma City Thunder,1,Made Shot,Driving Finger Roll Layup Shot,...,Less Than 8 ft.,0,0,6,1,1,20241115,OKC,PHX,392
4,Shot Chart Detail,22400018,85,1628983,Shai Gilgeous-Alexander,1610612760,Oklahoma City Thunder,1,Made Shot,Step Back Jump shot,...,16-24 ft.,20,141,144,1,1,20241115,OKC,PHX,294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101202,Shot Chart Detail,22401226,294,1628374,Lauri Markkanen,1610612762,Utah Jazz,2,Made Shot,Tip Dunk Shot,...,Less Than 8 ft.,0,0,0,1,1,20241216,LAC,UTA,103
101203,Shot Chart Detail,22401226,332,1628374,Lauri Markkanen,1610612762,Utah Jazz,3,Made Shot,Jump Shot,...,24+ ft.,23,230,22,1,1,20241216,LAC,UTA,692
101204,Shot Chart Detail,22401226,431,1628374,Lauri Markkanen,1610612762,Utah Jazz,3,Missed Shot,Jump Shot,...,24+ ft.,27,132,239,1,0,20241216,LAC,UTA,270
101205,Shot Chart Detail,22401226,464,1628374,Lauri Markkanen,1610612762,Utah Jazz,3,Missed Shot,Running Jump Shot,...,24+ ft.,26,197,176,1,0,20241216,LAC,UTA,161
101206,Shot Chart Detail,22401226,468,1628374,Lauri Markkanen,1610612762,Utah Jazz,3,Made Shot,Cutting Layup Shot,...,Less Than 8 ft.,3,-9,30,1,1,20241216,LAC,UTA,150

In [6]:
df = df.drop_duplicates(subset=['GAME_ID', 'PLAYER_ID', 'PERIOD', 'TIME_REMAINING_SEC', 'LOC_X', 'LOC_Y'])

In [7]:
print(df['SHOT_MADE_FLAG'].value_counts)

<bound method IndexOpsMixin.value_counts of 0         0
1         0
2         1
3         1
4         1
         ..
101202    1
101203    1
101204    0
101205    0
101206    1
Name: SHOT_MADE_FLAG, Length: 101192, dtype: int64>

In [8]:
print(df['ACTION_TYPE'].unique())
print(df['SHOT_ZONE_BASIC'].unique())
print(df['SHOT_TYPE'].unique())

<StringArray>
[          'Turnaround Fadeaway shot',                   'Pullup Jump shot',
                'Step Back Jump shot',     'Driving Finger Roll Layup Shot',
                 'Cutting Layup Shot',                 'Driving Layup Shot',
          'Running Pull-Up Jump Shot',    'Driving Floating Bank Jump Shot',
                          'Jump Shot',               'Turnaround Jump Shot',
                         'Layup Shot',     'Running Finger Roll Layup Shot',
                 'Running Layup Shot',                 'Floating Jump shot',
                 'Putback Layup Shot',                 'Fadeaway Jump Shot',
                 'Fadeaway Bank shot',         'Running Reverse Layup Shot',
                  'Running Jump Shot',         'Driving Reverse Layup Shot',
                          'Dunk Shot',                  'Running Dunk Shot',
         'Driving Floating Jump Shot',                     'Jump Bank Shot',
               'Turnaround Bank shot',                  'Cutting Dunk Shot',
                  'Driving Dunk Shot',                     'Tip Layup Shot',
                 'Reverse Layup Shot',     'Cutting Finger Roll Layup Shot',
             'Finger Roll Layup Shot',                  'Putback Dunk Shot',
               'Turnaround Hook Shot', 'Turnaround Fadeaway Bank Jump Shot',
           'Step Back Bank Jump Shot',                  'Driving Hook Shot',
             'Driving Bank Hook Shot',                     'Hook Bank Shot',
        'Running Alley Oop Dunk Shot',               'Alley Oop Layup shot',
                          'Hook Shot',                'Alley Oop Dunk Shot',
                      'Tip Dunk Shot',       'Running Alley Oop Layup Shot',
          'Driving Reverse Dunk Shot',          'Turnaround Bank Hook Shot',
                  'Reverse Dunk Shot',          'Running Reverse Dunk Shot']
Length: 48, dtype: str
<StringArray>
['In The Paint (Non-RA)',             'Mid-Range',     'Above the Break 3',
       'Restricted Area',         'Left Corner 3',        'Right Corner 3',
             'Backcourt']
Length: 7, dtype: str
<StringArray>
['2PT Field Goal', '3PT Field Goal']
Length: 2, dtype: str

In [9]:
df.to_csv('nba_shot_data_2024_25_cleaned.csv', index=False)